### ISSUE TITLE
Confusion with Automator.input_path()

### ISSUE THREAD

**Issue by grodino** [pypr/automan#23]
Hi !

First of all, thank you for this very useful module !

If the following example in the [tutorial](https://automan.readthedocs.io/en/latest/tutorial.html), I think that the name `input_path` is a bit confusing.
```
>>> import automate2
>>> squares = automate2.Squares(
...    simulation_dir='outputs',
...    output_dir='manuscript/figures/'
... )

>>> squares.input_path('1')
'outputs/squares/1'

>>> squares.input_path('1', 'stdout.txt')
'outputs/squares/1/stdout.txt'

>>> squares.output_path('output.txt')
'manuscript/figures/squares/output.txt'
```

Since `input_path` returns the name of the simulation joined to the `simulation_dir`, do you think it would be a good idea to rename it to `simulation_path` ? The old name could be kept and marked deprecated.

If you think it is a good idea, I'd be glad to do it !

+,
Augustin

**Comment by prabhuramachandran** [comment]
Hi @grodino -- yes this is a great idea, input and output are sometimes confusing.  So yes, a `simulation_path` sounds good to me while retaining the `input_path`.  If you are going to add this, please also document this in the tutorial.  Thank you and apologies for the slow response!
